In [236]:
import pandas as pd
import numpy as np
import tensorflow as tf 
import matplotlib.pyplot as plt

In [237]:
df=pd.read_csv("Train_3.csv")
print(df)
print(df["Team1_Innings"].isna().sum())


      Team1  Team2  Stadium  HostCountry Team1_Venue Team2_Venue  \
0         5      4       37            4        Home        Away   
1         1     14       84            7     Neutral     Neutral   
2         9     15       47            9        Home        Away   
3         7      2      102            6        Home        Away   
4         6      8       46            5        Home        Away   
...     ...    ...      ...          ...         ...         ...   
2503      5     15       89            3     Neutral     Neutral   
2504      1     14      138            0        Home        Away   
2505     14      5      135           15        Home        Away   
2506     15     14       64           16        Home        Away   
2507      1     10      111            0        Home        Away   

     Team1_Innings Team2_Innings MonthOfMatch  MatchWinner  
0           Second         First          Dec            4  
1            First        Second          Sep            1  


In [238]:
df["Team1_Innings"].replace({"First":1,"Second":2},inplace=True)
df["Team2_Innings"].replace({"First":1,"Second":2},inplace=True)
df["MonthOfMatch"].replace({"Jan":1,"Feb":2,"Mar":3,"Apr":4,"May":5,"Jun":6,"Jul":7,"Aug":8,"Sep":9,"Oct":10,"Nov":11,"Dec":12},inplace=True)
df["Team1_Venue"].replace({"Home":1,"Away":0,"Neutral":0},inplace=True)
df["Team2_Venue"].replace({"Home":1,"Away":0,"Neutral":0},inplace=True)
print(df)

      Team1  Team2  Stadium  HostCountry  Team1_Venue  Team2_Venue  \
0         5      4       37            4            1            0   
1         1     14       84            7            0            0   
2         9     15       47            9            1            0   
3         7      2      102            6            1            0   
4         6      8       46            5            1            0   
...     ...    ...      ...          ...          ...          ...   
2503      5     15       89            3            0            0   
2504      1     14      138            0            1            0   
2505     14      5      135           15            1            0   
2506     15     14       64           16            1            0   
2507      1     10      111            0            1            0   

      Team1_Innings  Team2_Innings  MonthOfMatch  MatchWinner  
0                 2              1            12            4  
1                 1            

C:\Users\shaik\AppData\Local\Temp\ipykernel_13332\3661811974.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Team1_Innings"].replace({"First":1,"Second":2},inplace=True)
C:\Users\shaik\AppData\Local\Temp\ipykernel_13332\3661811974.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Team1

In [239]:
y=df["MatchWinner"].to_numpy()
df.drop(["MatchWinner"],axis=1,inplace=True)
print(y)
print(df)

[ 4  1  9  2  6  5  9 13  9  5 14  4 10 10 12 14 10 13  4  4 15 10  9  9
 13  1  9 14  4  5 14 10  9  1 12  5 10 10 14  1 14  5 10  1  5  4  1 14
 13 12  9  1 10  4  1 10 10 12  5 13 10  3 10  1  0 13 14 13  4 12 13  9
 15  1  4 12 13  4  5 10  5 13 13 13  1 12  5 10  5  5  9  5  1  5  2  1
  9 12 13 13 13  9 14 10 10 10 14  5 14 12 14  7 12  5  4 13 10  5  4  2
  2  1  1 13  1 14 14  5  1 13 13 14 13 14  1  9  5 14 10  4  9  3 15 12
 12  2 14 12  1 13  5 12  1  4  5  2  6  2 12  1  4  9 12  5 12  6  5  1
 12  4 13  9  4  1 11  2  5  5  5  7 10  9  2 10  4 10  5 14  5 13 13  9
 14 10  4 10 10  9 12 13  2 13 13  5  4 13 14 15  1  9  1 10 13  2  4 13
  1 14 10  4 12  9  1 14 14 12  9  2  9  9  5  3 14 14  5 12 13  9  4 10
  2  5  5 12 10  5  5  1  4  1  9  4 10  1  5  7  1 11 14  1  1  4  1  5
 13  1  1 12  1 15  5  4  6  1 12  5 13 12 13  4 14  9 14  4 10  4 10 10
 13 13  5  2 12  4 12  4  5 12 14 12  9  1 10 12  9 14  1  4  1 10  1  0
  1 14  4 13 10  5 14 10 13 10  4  6  5 14  1  5 14

In [240]:
print(df["Team1"].nunique())

16


In [241]:
arr=df.to_numpy()
print(arr)

[[  5   4  37   4   1   0   2   1  12]
 [  1  14  84   7   0   0   1   2   9]
 [  9  15  47   9   1   0   1   2   2]
 [  7   2 102   6   1   0   1   2   8]
 [  6   8  46   5   1   0   1   2   8]
 [  5  13   3   4   1   0   2   1  11]
 [  9  12 149   9   1   0   1   2   2]
 [ 13  10  38  13   1   0   1   2   5]
 [  9  13  35   9   1   0   2   1   1]
 [  4   5  21   3   1   0   2   1   8]
 [ 14   1  11  15   1   0   2   1   6]
 [  4  10 130  14   0   0   1   2  12]
 [  9  10 103   9   1   0   1   2   2]
 [  5  10  75   4   1   0   1   2   4]
 [ 10  12  86  10   1   0   2   1  10]
 [ 14   9  58  15   1   0   2   1   6]
 [ 10  13   1  14   0   0   1   2   5]
 [ 13   9  36  13   1   0   2   1  12]
 [  4   5 142   3   1   0   1   2   6]
 [  4   1  93   3   1   0   2   1   6]
 [ 15   6  64  16   1   0   2   1   9]
 [ 10  13  48  12   0   0   2   1  12]
 [  9  10  38  13   0   0   2   1   5]
 [  9   1   8   9   1   0   1   2   2]
 [ 15  13  64  16   1   0   1   2  11]
 [  1  10 138   0   1   0

In [242]:
def normalize_data(X):
    mean = np.mean(X, axis=1)
    std = np.std(X, axis=1)
    
    # Normalize the data
    X_normalized=[]
    for i in range(X.shape[0]):
        X_normalized.append((X[i] - np.mean(X[i])) / np.std(X[i]))
    
    return np.array(X_normalized)

In [243]:
arr=normalize_dataset(arr)
print(arr)

-2 i is  0
-5 i is  1
-36 i is  2
-3 i is  3
0 i is  4
0 i is  5
0 i is  6
0 i is  7
6 i is  8
-6 i is  0
4 i is  1
10 i is  2
0 i is  3
0 i is  4
0 i is  5
0 i is  6
0 i is  7
3 i is  8
1 i is  0
5 i is  1
-26 i is  2
1 i is  3
0 i is  4
0 i is  5
0 i is  6
0 i is  7
-3 i is  8
0 i is  0
-7 i is  1
28 i is  2
-1 i is  3
0 i is  4
0 i is  5
0 i is  6
0 i is  7
2 i is  8
-1 i is  0
-1 i is  1
-27 i is  2
-2 i is  3
0 i is  4
0 i is  5
0 i is  6
0 i is  7
2 i is  8
-2 i is  0
3 i is  1
-70 i is  2
-3 i is  3
0 i is  4
0 i is  5
0 i is  6
0 i is  7
5 i is  8
1 i is  0
2 i is  1
75 i is  2
1 i is  3
0 i is  4
0 i is  5
0 i is  6
0 i is  7
-3 i is  8
5 i is  0
0 i is  1
-35 i is  2
5 i is  3
0 i is  4
0 i is  5
0 i is  6
0 i is  7
0 i is  8
1 i is  0
3 i is  1
-38 i is  2
1 i is  3
0 i is  4
0 i is  5
0 i is  6
0 i is  7
-4 i is  8
-3 i is  0
-4 i is  1
-52 i is  2
-4 i is  3
0 i is  4
0 i is  5
0 i is  6
0 i is  7
2 i is  8
6 i is  0
-8 i is  1
-62 i is  2
7 i is  3
0 i is  4
0 i is  5
0 i

C:\Users\shaik\AppData\Local\Temp\ipykernel_13332\2754979414.py:9: RuntimeWarning: invalid value encountered in scalar divide
  row[i]=row[i]/std[i]


ValueError: cannot convert float NaN to integer

In [ ]:
def split_indices(n,f,s):
    n_test=int(n*f)
    np.random.seed(s)
    idxs=np.random.permutation(n)
    return idxs[:n_test],idxs[n_test:]


In [ ]:
train,test=split_indices(arr.shape[0],0.3,42)
X_train=arr[train]
y_train=y[train]
X_test=arr[test]
y_test=y[test]
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
print(X_train)


[[ 12  13  26  12   1   0   1   2   2]
 [  7  10  16   3   0   0   1   2   9]
 [  4   9 138   0   0   0   2   1   1]
 [ 11   9  50  11   1   0   1   2   5]
 [  5  14   2   0   0   0   1   2  12]
 [  4  14 142   3   1   0   1   2   9]
 [  9  13 135  15   0   0   1   2   4]
 [  4  12 108   3   1   0   2   1   8]
 [  1  13 138   0   1   0   1   2   2]
 [  4   9  88   3   1   0   2   1   7]
 [  5  10 130  14   0   0   2   1   4]
 [  5  15  20   0   0   0   1   2   1]
 [  5   9  37   4   1   0   1   2  11]
 [ 10  14  86  10   1   0   2   1  11]
 [ 14   1  81  15   1   0   2   1   3]
 [ 14   1  80  15   1   0   1   2   5]
 [ 15   2  22  16   1   0   1   2   8]
 [  7   1 102   6   1   0   1   2   9]
 [ 15  13  64  16   1   0   1   2  11]
 [ 15   5  22  16   1   0   1   2   8]
 [ 12  15  25   3   0   0   1   2   6]
 [  9  14 149   9   1   0   2   1   1]
 [ 15   4  22  16   1   0   2   1  12]
 [  4   5  20   0   0   0   2   1   1]
 [ 10   2  51  10   1   0   1   2   9]
 [  4  15 142   3   1   0

In [ ]:
def encod(y,df):
    y_encod=[]
    for i in range(len(y)):
        if(y[i]==df['Team2'].iloc[i]):
            y_encod.append([0,1])
        else :
            y_encod.append([1,0])
    return np.array(y_encod)

y_train=encod(y_train,df)
y_test=encod(y_test,df)

print(y)

[ 4  1  9  2  6  5  9 13  9  5 14  4 10 10 12 14 10 13  4  4 15 10  9  9
 13  1  9 14  4  5 14 10  9  1 12  5 10 10 14  1 14  5 10  1  5  4  1 14
 13 12  9  1 10  4  1 10 10 12  5 13 10  3 10  1  0 13 14 13  4 12 13  9
 15  1  4 12 13  4  5 10  5 13 13 13  1 12  5 10  5  5  9  5  1  5  2  1
  9 12 13 13 13  9 14 10 10 10 14  5 14 12 14  7 12  5  4 13 10  5  4  2
  2  1  1 13  1 14 14  5  1 13 13 14 13 14  1  9  5 14 10  4  9  3 15 12
 12  2 14 12  1 13  5 12  1  4  5  2  6  2 12  1  4  9 12  5 12  6  5  1
 12  4 13  9  4  1 11  2  5  5  5  7 10  9  2 10  4 10  5 14  5 13 13  9
 14 10  4 10 10  9 12 13  2 13 13  5  4 13 14 15  1  9  1 10 13  2  4 13
  1 14 10  4 12  9  1 14 14 12  9  2  9  9  5  3 14 14  5 12 13  9  4 10
  2  5  5 12 10  5  5  1  4  1  9  4 10  1  5  7  1 11 14  1  1  4  1  5
 13  1  1 12  1 15  5  4  6  1 12  5 13 12 13  4 14  9 14  4 10  4 10 10
 13 13  5  2 12  4 12  4  5 12 14 12  9  1 10 12  9 14  1  4  1 10  1  0
  1 14  4 13 10  5 14 10 13 10  4  6  5 14  1  5 14

In [ ]:
input_shape = [X_train.shape[1]]

model = tf.keras.Sequential([

    tf.keras.layers.Dense(units=64, activation='relu',
                          input_shape=input_shape),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=2,activation='softmax')
])
model.summary()

c:\Users\shaik\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 64)             │           640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 2)              │           130 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,930 (19.26 KB)

 Trainable params: 4,930 (19.26 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
losses = model.fit(X_train, y_train,
                    epochs=50,
                    validation_split=0.2 )

Epoch 1/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.6248 - loss: 1.8860 - val_accuracy: 0.9205 - val_loss: 1.0979
Epoch 2/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9110 - loss: 0.8696 - val_accuracy: 0.8477 - val_loss: 0.3941
Epoch 3/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9006 - loss: 0.3418 - val_accuracy: 0.9205 - val_loss: 0.3229
Epoch 4/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9069 - loss: 0.3283 - val_accuracy: 0.9205 - val_loss: 0.3068
Epoch 5/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8961 - loss: 0.3571 - val_accuracy: 0.9205 - val_loss: 0.2971
Epoch 6/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9150 - loss: 0.3176 - val_accuracy: 0.9205 - val_loss: 0.2742
Epoch 7/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9115 - loss: 0.3194 - val_accuracy: 0.9205 - val_loss: 0.4449
Epoch 8/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9014 - loss: 0.4446 - val_accuracy: 0.9205 - val_loss

In [ ]:
y_pred=model.predict(X_test)
predicted_classes = tf.argmax(y_pred, axis=1)
print(predicted_classes.shape)

55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step
(1756,)


In [ ]:
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f'Test accuracy: {test_acc}')


24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9103 - loss: 0.2614 
Test accuracy: 0.9202127456665039


In [ ]:
def encod(y,df):
    y_encod=[]
    for i in range(len(y)):
        if(y[i]==df['Team2'].iloc[i]):
            y_encod.append("Team2")
        else :
            y_encod.append("Team1")
    return pd.DataFrame(y_encod)

y_ct=encod(y_train,df)
y_ct=y_ct.value_counts()
y_ct.plot(kind='bar',color=['blue','red'])
plt.title('Match Wins by Team')
plt.xlabel('Teams')
plt.ylabel('Number of Wins')
plt.show()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()